load("//tensorflow:tensorflow.bzl", "tf_cc_binary")

tf_cc_binary(
    name = "foo",
    srcs = ["foo.cc"],
    deps = [
        "//tensorflow/core:framework",
        "//tensorflow/core:tensorflow",
    ]
)
